name: temposage
description: A new Flutter project for managing activities and schedules.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^17.2.1
  table_calendar: ^3.0.9
  path_provider: ^2.1.1
  flutter_slidable: ^3.0.1
  provider: ^6.1.4
  json_annotation: ^4.8.1
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.4
  http: ^1.1.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.3

flutter:
  uses-material-design: true

  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
